### ISSUE TITLE
I would like a way to verify that my arch test is not a false-positive

### ISSUE THREAD

**Issue by boly38** [TNG/ArchUnit#708] opened 2021-10-29 12:34 UTC
Hi
I would like a way to check that my arch test is done with success and having (even approximatively) parsed expected target classes. (Sorry I didn't found the answer in doc).

Suppose a dev team member add an predicate to my arch test that result in **none match**. 
Then the check will be positive but without parsing any classes..

Example:
```
   ...{
        ArchRule myRule = methods()
                        .that().areDeclaredInClassesThat(annotatedWith(RestController.class))
                        .should(beAnnotatedWith(Operation.class));
        myRule.check(myJavaClasses);
    }

```
this method checks the documentation arround rest controller.
suppose this match 50 classes

if a third party can add a wrong predicate, the result match could go from 50 to 0 matches and the test will stay green..
```
.and().areDeclaredInClassesThat(annotatedWith(Lazy.class))
```
I would like to avoid that.
does exist a way to do that ?

Ideally I would like a count of matching classes like that:

```
assertThat( myRule.check(myJavaClasses ).nbMatches() ).isGreaterThan(10);
```

**Comment by codecholeric** [comment] 2021-10-30 14:43
I think this is a duplicate of #532. But unfortunately there is no way yet, even though it would be a great addition :disappointed: 
For classes you can already do 

```
classes().that()...
  .should()...
  .andShould().containNumberOfElements(greaterThanOrEqualTo(1))
```

For methods this does not exist yet (compare #179)
So if you want it for methods you would have to "steal" `com.tngtech.archunit.lang.conditions.ArchConditions.NumberOfElementsCondition` and adjust it to `JavaMethod` (or `JavaMember`) instead of `JavaClass` (in fact this condition should have been made generic right away, since it doesn't depend on the type of the element, but back then I only solved the use case for `JavaClass`)
Since there is already an issue to solve it generically and one to add this check method for the `members()...` API I'll close this issue for now. But feel free to reopen if you feel there is anything not yet covered by these issues!

**Closed by codecholeric** 2021-10-30 14:43 UTC

**Comment by boly38** [comment] 2021-10-30 18:32
Thanks @codecholeric I will check that tuesday.
it seems to meet my need.
If you do it generically it will be perfect 👏
