### ISSUE TITLE
Any clues on why this error is..

### ISSUE THREAD

**Issue by nagkumar** [TNG/ArchUnit#926] opened 2022-07-30 13:00 UTC
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 17.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'archunit' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 18 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.tngtech.archunit.base.ClassLoaders.loadClass(ClassLoaders.java:31)
	at com.tngtech.archunit.junit.internal.ElementResolver.classOf(ElementResolver.java:107)
	at com.tngtech.archunit.junit.internal.ElementResolver.resolveClass(ElementResolver.java:56)
	at com.tngtech.archunit.junit.internal.ArchUnitTestDescriptor.resolve(ArchUnitTestDescriptor.java:67)
	at com.tngtech.archunit.junit.internal.ArchUnitTestEngine.lambda$resolveRequestedClasses$3(ArchUnitTestEngine.java:125)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.tngtech.archunit.junit.internal.ArchUnitTestEngine.resolveRequestedClasses(ArchUnitTestEngine.java:125)
	at com.tngtech.archunit.junit.internal.ArchUnitTestEngine.discover(ArchUnitTestEngine.java:87)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 29 more
Caused by: java.lang.NullPointerException: URL must not be null
	at com.tngtech.archunit.thirdparty.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
	at com.tngtech.archunit.library.plantuml.PlantUmlParser.parse(PlantUmlParser.java:41)
	at com.tngtech.archunit.library.plantuml.PlantUmlArchCondition.create(PlantUmlArchCondition.java:214)
	at com.tngtech.archunit.library.plantuml.PlantUmlArchCondition.adhereToPlantUmlDiagram(PlantUmlArchCondition.java:186)
	at com.tngtech.archunit.examples.test.PlantUmlArchitectureTest.<clinit>(PlantUmlArchitectureTest.java:29)
	... 49 more
```
Wrap lines

**Comment by nagkumar** [comment] 2022-07-30 13:01
My build file is 

```
import java.awt.*

plugins {
    id 'java'
    id 'maven-publish'
    id("com.github.ben-manes.versions") version "+"
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation 'javax.annotation:javax.annotation-api:+'
    implementation 'org.apache.geronimo.specs:geronimo-ejb_3.1_spec:+'
    implementation 'org.apache.geronimo.specs:geronimo-jpa_2.0_spec:+'
    implementation 'joda-time:joda-time:+'
    implementation 'org.springframework:spring-beans:+'

    implementation 'com.google.inject:guice:+'
    implementation("com.google.guava:guava:+")
    testImplementation("com.tngtech.archunit:archunit-junit5:+")
}

test {
    useJUnitPlatform()
}

tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true
}

tasks.register("openTR") {
    doLast {
	Desktop.getDesktop().browse(new File("$buildDir/reports/tests/test/index.html").toURI())
    }
}

defaultTasks("clean", "test", "openTR")
```

**Comment by nagkumar** [comment] 2022-07-30 13:16
not realted to this repo

**Comment by hankem** [comment] 2022-07-31 22:37
Is there anything that you think should be improved on ArchUnit's side?
If not: can we close this issue? 😉

**Comment by nagkumar** [comment] 2022-08-01 03:02
Maybe if the exception can be give where **all paths it searched**  as part of this error message

` TestEngine with ID 'archunit' failed to discover tests`

more valuable.

Beyond this, you can close this..

**Comment by codecholeric** [comment] 2022-08-01 08:57
I think this is tricky, because the exception comes from the platform, not from ArchUnit's engine. And if a class completely crashes on initialization there is not much to do. But in the end the root cause is reported very clearly

```
Caused by: java.lang.NullPointerException: URL must not be null
	at com.tngtech.archunit.thirdparty.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
	at com.tngtech.archunit.library.plantuml.PlantUmlParser.parse(PlantUmlParser.java:41)
```

Just that you have to follow down the stacktraces makes it a little tricky, but I don't think there is much we can do there, because it just is a nested process by the way running the JUnit test is set up. So I'd close it for now unless somebody has a concrete idea what to do within ArchUnit.

**Closed by codecholeric** 2022-08-01 08:57 UTC
