### ISSUE TITLE
Use of System.lineSeparator() prevents development on heterogenous systems

### ISSUE THREAD

**Issue by gopf** [TNG/ArchUnit#508] opened 2021-01-12 11:51 UTC
We have just started using ArchUnit in a small way, and have existing violations that we need to freeze.

Storing the currently frozen rules in the project along with the source seems to be the right thing to do. Getting that to work is a little bit tricky as I couldn't find a `freeze.store.default.path` setting for this use case that works both locally and in the automated build, but I have a tolerable workaround (copy with variable expansion from Ant, use variable setting in the local run target to override).

Unfortunately we have some developers that use Windows and some that use Macs, and the stored violations can't be shared between these two groups as the line endings vary. This is a blocker, and means that we can't really use ArchUnit.

**Comment by hankem** [comment] 2021-01-12 12:01
This might be a duplicate of #458?

**Comment by gopf** [comment] 2021-01-12 16:47
It's definitely related, but #458 relates more to the rule itself as key. Our rules are simple one-liners so the key isn't a problem, rather it's the violations themselves (which seem to be often multiline descriptions).

**Comment by codecholeric** [comment] 2021-01-12 19:11
Hmm, there is definitely some escaping / replacing of Windows linebreaks in place there, but maybe it's not enough :thinking: Do you have by any chance a minimal sample of a problematic scenario that works on Windows, but does not on Linux? (or vice versa, but since I'm using Linux myself it would be easier to reproduce, if I have a sample that works on Windows, but not on Linux :wink:)
I'm just a little puzzled, because there is an ArchUnit integration test, that has a checked in violation store file, and that works on Linux and Windows :thinking: 
You can compare [FrozenRulesTest](https://github.com/TNG/ArchUnit/blob/master/archunit-example/example-plain/src/test/java/com/tngtech/archunit/exampletest/FrozenRulesTest.java) / [the respective violation store](https://github.com/TNG/ArchUnit/tree/master/archunit-example/example-plain/src/test/resources/frozen) which works as a freeze input

* [on Ubuntu](https://github.com/TNG/ArchUnit/runs/1674208161?check_suite_focus=true#step:6:7650)
* [on MacOS](https://github.com/TNG/ArchUnit/runs/1674208214?check_suite_focus=true#step:6:8960)
* [on Windows](https://github.com/TNG/ArchUnit/runs/1674208292?check_suite_focus=true#step:6:7547)

I.e. the integration test `FrozenRulesTest` produces exactly the same violations on Linux, MacOS and Windows when I run them in different CI environments. But the file has been created on Linux, so maybe the problem occurs, if Windows / MacOS users store the file with different line endings? :thinking: 

To solve the `freeze.store.default.path` in different environments I usually override it via 

```
-Darchunit.freeze.store.default.path=localPath
``` 

(see https://www.archunit.org/userguide/html/000_Index.html#_overriding_configuration) Depending on your build tool you can configure the test task to pass this system property.

**Comment by gopf** [comment] 2021-01-12 20:49
Thanks for the quick response. I wrote a little test Maven project that runs in a similar way to our real project: https://github.com/gopf/archunit-test

The store was frozen on my Mac, and the test runs fine there. If I run mvn clean test on a Windows machine it fails, though.

In this case I fix up the archunit.properties with a Maven filter so the project basedir is used. That works pretty well.

**Comment by gopf** [comment] 2021-01-12 20:59
To make it easier, I checked in the store generated on Windows. This succeeds on Windows but fails on the Mac.

**Comment by codecholeric** [comment] 2021-01-15 10:28
Thanks a lot!! I'll use that sample to see how to fix it :smiley: And try to fix #458 on the way, since that goes very much in the same direction.

**Closed** 2021-01-27 21:52 UTC
