### ISSUE TITLE
Enum classes not recognized as enums and with with wrong access modifiers

### ISSUE THREAD

**Issue by kosciuszkopiotr** [TNG/ArchUnit#1233] opened 2024-01-18 11:25 UTC
Hello,
I'm using following code for rule:
```
           classes()
                    .that()
                    .haveSimpleNameContaining("Command")
                    .and()
                    .doNotHaveModifier(JavaModifier.ABSTRACT)
                    .should(new ArchCondition<>("In command package only result, request and command can be public") {
                        @Override
                        public void check(JavaClass item, ConditionEvents events) {
                            JavaPackage aPackage = item.getPackage();
                            long publicClasses = aPackage.getClasses().stream()
                                    .filter(clazz -> clazz.getModifiers().contains(JavaModifier.PUBLIC))
                                    .filter(clazz-> !clazz.isNestedClass())
                                    .filter(clazz -> Stream.of("Result", "Request", "Command")
                                            .noneMatch(suffix -> clazz.getName().endsWith(suffix)))
                                    .count();
                            if (publicClasses > 0) {
                                events.add(SimpleConditionEvent.violated(item.getPackage(), item.getPackage() + ": package warning - only result, request and command classes should be public "));
                            }
                        }
                    })
                    .as("In command package only result, request and command can be public")
```

As per description, the objective of the rule is to keep only selected public classes in packages with "command" in name. The issue is that this rule fails for package-private access enums and even shows those enums with wrong descriptors (Array):
![Screenshot 2024-01-18 121657](https://github.com/TNG/ArchUnit/assets/29351489/4a195467-4522-4a3f-9c7f-86c1953af6fb)
If I make one of the enums public (I have two cases as per screenshot), then this enum will pop up twice in the condition check.
Could you please advise?
Best regards!

**Comment by rweisleder** [comment] 2024-01-22 16:48
This looks like a bug in `JavaPackage.getClasses()`, because the method returns the type and the corresponding array type.

```java
class GH1233 {

    @Test
    void test() {
        JavaClass javaClass = new ClassFileImporter().importClass(GH1233.class);
        Set<JavaClass> classesInPackage = javaClass.getPackage().getClasses();
        assertThat(classesInPackage).extracting(JavaClass::getSimpleName).containsExactly("GH1233");
    }

    void foo(GH1233[] bar) {
    }
}
```
This test fails, because `classesInPackage` is `["GH1233", "GH1233[]"]`

@kosciuszkopiotr: maybe you can rewrite your rule like this:
```java
classes()
    .that(describe("reside in command package", javaClass -> javaClass.getPackage().getClasses().stream().anyMatch(simpleNameContaining("Command"))))
    .and().areTopLevelClasses()
    .and(not(have(modifier(ABSTRACT))))
    .and(not(have(simpleNameEndingWith("Result").or(simpleNameEndingWith("Request")).or(simpleNameEndingWith("Command")))))
    .should().notBePublic();
```

**Comment by kosciuszkopiotr** [comment] 2024-01-23 16:39
This works! Thanks a lot :)

**Comment by codecholeric** [comment] 2024-03-06 21:51
> This looks like a bug in `JavaPackage.getClasses()`

AFAIR this is by design, you can argue if it's the best design of course 🤔 Cause at some point we decided that for most purposes an array should be considered to have the same package as the corresponding component type (as opposed to the Reflection API) and on the other hand all types found during the import are sorted into their respective package. So if you cause an import of an array type, like `GH1233[]` in your case, then this will be sorted into the same `JavaPackage` as `GH1233`. I'm not sure what would be a better behavior though 🤷 Every option seems possibly confusing depending on the circumstances...

**Comment by codecholeric** [comment] 2024-11-10 11:04
Gonna close this for now as it works "as intended" at the moment. Feel free to reopen if you want to discuss adjustments there (or alternatively start a GitHub discussion).

**Closed by codecholeric** 2024-11-10 11:04 UTC
