### ISSUE TITLE
JUnit 5 `@Order` support

### ISSUE THREAD

**Issue by jvwilge** [TNG/ArchUnit#852] opened 2022-04-20 07:22 UTC
Is it possible to support `@Order` on class level in ArchUnit?

I got`@Tag` working with `@ArchTag`, but by reading [this comment](https://github.com/TNG/ArchUnit/issues/645#issuecomment-896946178) I'm afraid it is hard to support `@Order` because tag is just on/off and order is a bit more complicated. But maybe there's hope 😄 

The reason I want to use `@Order` is that we want to run fast tests first so our build breaks earlier in case of any errors. The ArchUnit test is our slowest unit test (which is fine since it's quite extensive) but it always runs first, so we want to run it as the final unit test.

Note that we use `@Order` on class level like described [here](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order-classes) with a Gradle build.
(in short: creating the `junit-platform.properties` file and annotating the **class** with `@Order`)

Thank you for your help!

**Comment by codecholeric** [comment] 2022-04-20 17:26
One problem is that we shouldn't depend on the Jupiter API and `@Order` is part of this. So if we would support this, it would have to be an ArchUnit own annotation (and then I'm wondering how this would work between different engines anyway :thinking: Because ArchUnit has its own `TestEngine` and `@Order` will only be understood by the Jupiter Engine. The reason ArchUnit runs first might just be because of the order in which the `ServiceLoader` loads the `TestEngines` :man_shrugging:)

Any reason not to just have a separate test task then for the ArchUnit tests? You could exclude the ArchUnit tests from the first test task and only include them in the second, then control the order via task dependencies?

**Comment by codecholeric** [comment] 2022-04-20 17:27
The easiest way could also be to exclude the ArchUnit Engine from the first task and only include the ArchUnit Engine in the second task...

**Comment by jvwilge** [comment] 2022-04-21 05:44
Thank you for your swift reply. I was afraid this was the case, but now at least I can stop searching and maybe save someone else some time here 😄 

Your suggestion was my second plan, it's maybe even nicer since ArchUnit tests act on a different perspective of the code.

For the Gradle users I came up with this solution:

```groovy
test {
    useJUnitPlatform()
    exclude '**/*ArchUnitTest.class'
}

task archUnitTest(type: Test) {
    useJUnitPlatform()

    include '**/*ArchUnitTest.class'
    group 'verification'
    description 'ArchUnit tests'
}

check.dependsOn archUnitTest

//depend on `test`, not `testClasses` since after `testClasses` the tasks can run independently
archUnitTest.dependsOn testClasses
```

Thanks again for your help, and keep up the good work 👍

**Comment by codecholeric** [comment] 2022-04-22 09:49
As mentioned, if you don't want to depend on file patterns, you could also do

```
test {
    useJUnitPlatform {
        excludeEngines('archunit')
    }
}

task archUnitTest(type: Test) {
    useJUnitPlatform{
        includeEngines('archunit')
    }

    group 'verification'
    description 'ArchUnit tests'
}
```

**Comment by codecholeric** [comment] 2022-04-22 16:09
Yeah, you're right about that, it will only distinguish between JUnit Jupiter (i.e. `@Test`) and the `ArchUnitTestEngine` (i.e. `@ArchTest`). If you have ArchUnit tests that run as plain `@Test` methods they would run with your default test task then!

**Comment by codecholeric** [comment] 2022-06-12 12:43
I'm going to close this issue for now since I think the problem is solved, right? If not feel free to reopen :wink:

**Closed by codecholeric** 2022-06-12 12:43 UTC
