### ISSUE TITLE
Gradle TestFilter and ArchUnit Tests

### ISSUE THREAD

**Issue by SoerenKn** [TNG/ArchUnit#743] opened 2021-12-17 14:54 UTC
I noticed, that the gradle TestFilter in the test Task does not work as expected in combination with ArchUnit.
I have a project where we distinguish between unit and integration tests by a naming convention.
We have therefore adjusted the gradle test task with a filter so that it does not execute test classes that have the suffix "IT".

```
test {
	useJUnitPlatform()
        filter {
		excludeTestsMatching "*IT"
	}
}
```

But with this filter in place, the archunit tests never get executed with the gradle test command. It doesn't matter what name the test has or what is excluded in the filter. The test gets only executed if I remove the excludeTestsMatching filter. 

I tried this with the provided OnionArchitectureTest, the class looks like this:

```
@AnalyzeClasses(packages = "com.myapp.demo")
public class OnionArchitectureTest {

	@ArchTest
	static final ArchRule onion_architecture_is_respected = onionArchitecture()
		.domainModels("com.myapp.demo.domain..")
		.domainServices("com.myapp.demo.application..")
		.applicationServices("com.myapp.demo..")
		.adapter("in", "com.myapp.demo.adapter.in..") 
		.adapter("out", "com.myapp.demo.adapter.out.."); 
}
```
Is this something that can be fixed? For now I use the includeTestsMatching filter as a workaround.

Kind regards,
Sören

**Comment by codecholeric** [comment] 2021-12-20 07:52
Thanks for reporting this! :+1: Unfortunately, the issue is IMHO not with ArchUnit but with the Gradle JUnit Platform integration. So I can't directly fix this. I opened an issue here: https://github.com/gradle/gradle/issues/19352

**Comment by codecholeric** [comment] 2022-01-12 11:02
This should be fixed by https://github.com/gradle/gradle/issues/19352, so I'm gonna close this issue for now since there is nothing more we can do on the ArchUnit side.

**Closed by codecholeric** 2022-01-12 11:02 UTC

**Comment by SoerenKn** [comment] 2022-01-12 11:54
Thank you for taking care of this 👍
