### ISSUE TITLE
Tests fail on Windows because of illegal file URIs

### ISSUE THREAD

**Issue by rweisleder** [TNG/ArchUnit#58] opened 2018-01-02 20:24 UTC
I forked the repository and executed a build with `clean build -PallTests`. Without any changes the following tests fail on Windows because of illegal file URIs.

```
:archunit:test

com.tngtech.archunit.core.importer.ClassFileImporterSlowTest > imports_jars FAILED
    java.lang.IllegalArgumentException: Illegal character in opaque part at index 5: file:\Users\xxxx\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar
        at java.net.URI.create(URI.java:852)
        at com.tngtech.archunit.core.importer.Location.newFileUri(Location.java:164)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:143)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importJars(ClassFileImporter.java:112)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importJars(ClassFileImporter.java:105)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importJar(ClassFileImporter.java:100)
        at com.tngtech.archunit.core.importer.ClassFileImporterSlowTest.imports_jars(ClassFileImporterSlowTest.java:60)

        Caused by:
        java.net.URISyntaxException: Illegal character in opaque part at index 5: file:\Users\xxxx\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar
            at java.net.URI$Parser.fail(URI.java:2848)
            at java.net.URI$Parser.checkChars(URI.java:3021)
            at java.net.URI$Parser.parse(URI.java:3058)
            at java.net.URI.<init>(URI.java:588)
            at java.net.URI.create(URI.java:850)
            ... 6 more

com.tngtech.archunit.core.importer.ClassFileImporterTest > ImportOptions_are_respected FAILED
    java.lang.IllegalArgumentException: Illegal character in opaque part at index 5: file:\Users\xxxx\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar
        at java.net.URI.create(URI.java:852)
        at com.tngtech.archunit.core.importer.Location.newFileUri(Location.java:164)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:143)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importJars(ClassFileImporter.java:112)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importJars(ClassFileImporter.java:105)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importJar(ClassFileImporter.java:100)
        at com.tngtech.archunit.core.importer.ClassFileImporterTest.ImportOptions_are_respected(ClassFileImporterTest.java:1757)

        Caused by:
        java.net.URISyntaxException: Illegal character in opaque part at index 5: file:\Users\xxxx\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar
            at java.net.URI$Parser.fail(URI.java:2848)
            at java.net.URI$Parser.checkChars(URI.java:3021)
            at java.net.URI$Parser.parse(URI.java:3058)
            at java.net.URI.<init>(URI.java:588)
            at java.net.URI.create(URI.java:850)
            ... 6 more

com.tngtech.archunit.core.importer.ClassFileSourceTest > classes_in_JAR_are_filtered[0: [/one/Foo.class, /one/Bar.class, /two/Bar.class], com.tngtech.archunit.core.importer.ImportOptions@22bf94fb, [/one/Foo.class, /one/Bar.class, /two/Bar.class]] FAILED
    java.lang.IllegalArgumentException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878364045828424399998574865074908\test.jar
        at java.net.URI.create(URI.java:852)
        at com.tngtech.archunit.core.importer.Location.newFileUri(Location.java:164)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:143)
        at com.tngtech.archunit.core.importer.ClassFileSourceTest.classes_in_JAR_are_filtered(ClassFileSourceTest.java:62)

        Caused by:
        java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878364045828424399998574865074908\test.jar
            at java.net.URI$Parser.fail(URI.java:2848)
            at java.net.URI$Parser.checkChars(URI.java:3021)
            at java.net.URI$Parser.parse(URI.java:3058)
            at java.net.URI.<init>(URI.java:588)
            at java.net.URI.create(URI.java:850)
            ... 3 more

com.tngtech.archunit.core.importer.ClassFileSourceTest > classes_in_JAR_are_filtered[1: [/one/Foo.class, /one/Bar.class, /two/Bar.class], com.tngtech.archunit.core.importer.ImportOptions@1ae7f181, [/one/Foo.class, /one/Bar.class]] FAILED
    java.lang.IllegalArgumentException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878372910508525595324178910651973\test.jar
        at java.net.URI.create(URI.java:852)
        at com.tngtech.archunit.core.importer.Location.newFileUri(Location.java:164)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:143)
        at com.tngtech.archunit.core.importer.ClassFileSourceTest.classes_in_JAR_are_filtered(ClassFileSourceTest.java:62)

        Caused by:
        java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878372910508525595324178910651973\test.jar
            at java.net.URI$Parser.fail(URI.java:2848)
            at java.net.URI$Parser.checkChars(URI.java:3021)
            at java.net.URI$Parser.parse(URI.java:3058)
            at java.net.URI.<init>(URI.java:588)
            at java.net.URI.create(URI.java:850)
            ... 3 more

com.tngtech.archunit.core.importer.ClassFileSourceTest > classes_in_JAR_are_filtered[2: [/one/Foo.class, /one/Bar.class, /two/Bar.class], com.tngtech.archunit.core.importer.ImportOptions@7de272a, [/two/Bar.class]] FAILED
    java.lang.IllegalArgumentException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp987837304491962-8304586973681892963\test.jar
        at java.net.URI.create(URI.java:852)
        at com.tngtech.archunit.core.importer.Location.newFileUri(Location.java:164)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:143)
        at com.tngtech.archunit.core.importer.ClassFileSourceTest.classes_in_JAR_are_filtered(ClassFileSourceTest.java:62)

        Caused by:
        java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp987837304491962-8304586973681892963\test.jar
            at java.net.URI$Parser.fail(URI.java:2848)
            at java.net.URI$Parser.checkChars(URI.java:3021)
            at java.net.URI$Parser.parse(URI.java:3058)
            at java.net.URI.<init>(URI.java:588)
            at java.net.URI.create(URI.java:850)
            ... 3 more

com.tngtech.archunit.core.importer.ClassFileSourceTest > classes_in_JAR_are_filtered[3: [/one/Foo.class, /one/Bar.class, /two/Bar.class], com.tngtech.archunit.core.importer.ImportOptions@732cfbe1, [/one/Bar.class, /two/Bar.class]] FAILED
    java.lang.IllegalArgumentException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878373187069975548690689213990652\test.jar
        at java.net.URI.create(URI.java:852)
        at com.tngtech.archunit.core.importer.Location.newFileUri(Location.java:164)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:143)
        at com.tngtech.archunit.core.importer.ClassFileSourceTest.classes_in_JAR_are_filtered(ClassFileSourceTest.java:62)

        Caused by:
        java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878373187069975548690689213990652\test.jar
            at java.net.URI$Parser.fail(URI.java:2848)
            at java.net.URI$Parser.checkChars(URI.java:3021)
            at java.net.URI$Parser.parse(URI.java:3058)
            at java.net.URI.<init>(URI.java:588)
            at java.net.URI.create(URI.java:850)
            ... 3 more

com.tngtech.archunit.core.importer.ClassFileSourceTest > classes_in_JAR_are_filtered[4: [/one/Foo.class, /one/Bar.class, /two/Bar.class], com.tngtech.archunit.core.importer.ImportOptions@2deaa133, []] FAILED
    java.lang.IllegalArgumentException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878373309837588610823013150992030\test.jar
        at java.net.URI.create(URI.java:852)
        at com.tngtech.archunit.core.importer.Location.newFileUri(Location.java:164)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:143)
        at com.tngtech.archunit.core.importer.ClassFileSourceTest.classes_in_JAR_are_filtered(ClassFileSourceTest.java:62)

        Caused by:
        java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\xxxx\AppData\Local\Temp\archtmp9878373309837588610823013150992030\test.jar
            at java.net.URI$Parser.fail(URI.java:2848)
            at java.net.URI$Parser.checkChars(URI.java:3021)
            at java.net.URI$Parser.parse(URI.java:3058)
            at java.net.URI.<init>(URI.java:588)
            at java.net.URI.create(URI.java:850)
            ... 3 more

com.tngtech.archunit.core.importer.LocationTest > initializationError FAILED
    java.lang.Error: Cannot explode 'LocationTest.JAR_protocol_is_added_to_file_urls_that_point_to_JARs' using 'file_locations_pointing_to_jar' due to: Exception while invoking dataprovider method 'file_locations_pointing_to_jar': Illegal character in authority at index 7: file://C:\Users\xxxx\AppData\Local\Temp\archtmp9878411977992676820986918056713005\test.jar

        Caused by:
        java.lang.IllegalArgumentException: Exception while invoking dataprovider method 'file_locations_pointing_to_jar': Illegal character in authority at index 7: file://C:\Users\xxxx\AppData\Local\Temp\archtmp9878411977992676820986918056713005\test.jar

            Caused by:
            java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://C:\Users\xxxx\AppData\Local\Temp\archtmp9878411977992676820986918056713005\test.jar
                at java.net.URI.create(URI.java:852)
                at com.tngtech.archunit.core.importer.LocationTest.file_locations_pointing_to_jar(LocationTest.java:64)

                Caused by:
                java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\Users\xxxx\AppData\Local\Temp\archtmp9878411977992676820986918056713005\test.jar
                    at java.net.URI$Parser.fail(URI.java:2848)
                    at java.net.URI$Parser.parseAuthority(URI.java:3186)
                    at java.net.URI$Parser.parseHierarchical(URI.java:3097)
                    at java.net.URI$Parser.parse(URI.java:3053)
                    at java.net.URI.<init>(URI.java:588)
                    at java.net.URI.create(URI.java:850)
                    ... 1 more

2945 tests completed, 8 failed
:archunit:test FAILED
```

**Comment by codecholeric** [comment] 2018-01-02 23:20
Oh, sorry about that, I don't have any Windows platform to run the tests on, but I'll try to look into it (I had fixed them, a while back, but without a Windows CI, it's hard to keep the code...)
I definitely need to somehow set up some CI platform where I can run Windows on.

**Comment by codecholeric** [comment] 2018-01-05 18:22
I've tried to fix the problem, can you verify, that the build runs successfully on Windows now?

**Comment by rweisleder** [comment] 2018-01-08 09:46
Some tests still fail. The reason could be that my repository is on drive `d:` and the gradle cache is on drive `c:`

```
:archunit:test

com.tngtech.archunit.core.importer.ClassFileImporterSlowTest > imports_jars FAILED
    java.io.FileNotFoundException: \Users\xxxx\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar (Das System kann den angegebenen Pfad nicht finden)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at com.tngtech.archunit.core.importer.ClassFileImporterTest.jarFileOf(ClassFileImporterTest.java:1767)
        at com.tngtech.archunit.core.importer.ClassFileImporterSlowTest.imports_jars(ClassFileImporterSlowTest.java:60)

com.tngtech.archunit.core.importer.ClassFileImporterTest > ImportOptions_are_respected FAILED
    java.io.FileNotFoundException: \Users\xxxx\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar (Das System kann den angegebenen Pfad nicht finden)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at com.tngtech.archunit.core.importer.ClassFileImporterTest.jarFileOf(ClassFileImporterTest.java:1767)
        at com.tngtech.archunit.core.importer.ClassFileImporterTest.ImportOptions_are_respected(ClassFileImporterTest.java:1757)

2958 tests completed, 2 failed
```

**Comment by codecholeric** [comment] 2018-01-08 14:15
You are right, the test utility code was a little shady. Unfortunately Java is so lenient, that this did not fail, as long as the code resided on `C:` which is unfortunately the drive I've set up my windows checkout + Windows CI environment \*sigh\*
I've tried to clean up this utility code to resolve the Jar file in a platform independent way. I'd appreciate it, if you could give it one more try.
Anyway, thanks a lot for helping me to find these platform dependent test problems :smiley: I hope we'll soon have them all...

**Comment by rweisleder** [comment] 2018-01-08 14:47
hm... one failing test remains, but this didn't fail before
```
:archunit:test

com.tngtech.archunit.core.importer.ClassFileImporterTest > imports_classes_outside_of_the_classpath FAILED
    java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: D:\workspace\github\ArchUnit\archunit\build\classes\java\test\com\tngtech\archunit\core\importer\testexamples\outsideofclasspath\ChildClass$MySeed.class

        Caused by:
        java.nio.file.FileAlreadyExistsException: D:\workspace\github\ArchUnit\archunit\build\classes\java\test\com\tngtech\archunit\core\importer\testexamples\outsideofclasspath\ChildClass$MySeed.class

2958 tests completed, 1 failed
```

Exception from `build/test-results/test`
```
java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: D:\workspace\github\ArchUnit\archunit\build\classes\java\test\com\tngtech\archunit\core\importer\testexamples\outsideofclasspath\ChildClass$MySeed.class
	at com.tngtech.archunit.testutil.OutsideOfClassPathRule.after(OutsideOfClassPathRule.java:110)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	... snip ...
Caused by: java.nio.file.FileAlreadyExistsException: D:\workspace\github\ArchUnit\archunit\build\classes\java\test\com\tngtech\archunit\core\importer\testexamples\outsideofclasspath\ChildClass$MySeed.class
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:343)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at com.tngtech.archunit.testutil.OutsideOfClassPathRule.moveMatchingFilesDeleteRest(OutsideOfClassPathRule.java:78)
	at com.tngtech.archunit.testutil.OutsideOfClassPathRule.after(OutsideOfClassPathRule.java:108)
	... 40 more
```

**Comment by codecholeric** [comment] 2018-01-10 00:12
Yeah, I've seen that, too :frowning_face: 
That's some flaky test, it fails only on Windows, but only every xth time, and seemingly only, if all tests are ran together (at least I couldn't reproduce it, when I ran the test class alone 20x in a row).
I think that has something to do with the Windows file system as well, I've tried to add assertions to make the test fail earlier, but it still fails at the same point with the same message.
Anyway, I'll look into it, once I find the time (which might be a couple of days...)

**Comment by codecholeric** [comment] 2018-06-03 11:36
I think I finally found the last problem, at least now I could run all core-tests in a row for > 10 minutes without any problems on my Windows VirtualBox, while before it would reliably crash when running all core-tests in a row for 2-3 minutes.
Maybe you can do some checks if the suite now runs correctly on a Windows system.
Otherwise I would finally close this issue :wink:

**Comment by rweisleder** [comment] 2018-06-04 16:46
I also ran the build against the current master ~20 times, no problems. :)

**Comment by codecholeric** [comment] 2018-06-04 18:18
Yeeeess!! :smiley: 
I'll call that good enough for now, if another problem should show, I'll open a new issue. Besides that, I'll make sure to finally set up that Windows CI environment in a sustainable manner to make sure I'll catch these things faster in the future. (I had to get rid of my old environment, thus #73 slipped through for a couple of weeks :frowning_face:)

**Closed by codecholeric** 2018-06-04 18:18 UTC
