### ISSUE TITLE
Can't register multiple enclosing classes, this is likely a bug!

### ISSUE THREAD

**Issue by froque** [TNG/ArchUnit#637] opened 2021-07-15 14:31 UTC
```
2021-07-15 15:29:51 [main] WARN  c.t.a.c.i.ClassFileProcessor:222 - Error during import from jar:file:/home/froque/.m2/repository/com/google/firebase/firebase-admin/7.3.0/firebase-admin-7.3.0.jar!/com/google/firebase/messaging/MulticastMessage$1.class, falling back to simple import
java.lang.IllegalArgumentException: Can't register multiple enclosing classes, this is likely a bug!
	at com.tngtech.archunit.thirdparty.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com.tngtech.archunit.core.importer.ClassFileImportRecord$EnclosingDeclarationsByInnerClasses.registerEnclosingClass(ClassFileImportRecord.java:297)
	at com.tngtech.archunit.core.importer.ClassFileImportRecord.setEnclosingClass(ClassFileImportRecord.java:119)
	at com.tngtech.archunit.core.importer.ClassFileProcessor$ClassDetailsRecorder.registerEnclosingClass(ClassFileProcessor.java:140)
	at com.tngtech.archunit.core.importer.JavaClassProcessor.visitInnerClass(JavaClassProcessor.java:185)
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:717)
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.tngtech.archunit.core.importer.ClassFileProcessor$UriImporterOfProcessor.tryImport(ClassFileProcessor.java:219)
	at com.tngtech.archunit.core.importer.resolvers.ClassResolverFromClasspath.tryResolve(ClassResolverFromClasspath.java:51)
	at com.tngtech.archunit.core.importer.ImportedClasses.getOrResolve(ImportedClasses.java:57)
	at com.tngtech.archunit.core.importer.ImportedClasses$1.get(ImportedClasses.java:80)
	at com.tngtech.archunit.core.importer.DomainBuilders$JavaMemberBuilder.get(DomainBuilders.java:169)
	at com.tngtech.archunit.core.importer.DomainBuilders$JavaCodeUnitBuilder.asJavaClasses(DomainBuilders.java:335)
	at com.tngtech.archunit.core.importer.DomainBuilders$JavaCodeUnitBuilder.getParameters(DomainBuilders.java:305)
	at com.tngtech.archunit.core.domain.JavaCodeUnit.<init>(JavaCodeUnit.java:69)
	at com.tngtech.archunit.core.domain.JavaConstructor.<init>(JavaConstructor.java:42)
	at com.tngtech.archunit.core.domain.DomainObjectCreationContext.createJavaConstructor(DomainObjectCreationContext.java:118)
	at com.tngtech.archunit.core.importer.DomainBuilders$JavaConstructorBuilder.construct(DomainBuilders.java:371)
	at com.tngtech.archunit.core.importer.DomainBuilders$JavaConstructorBuilder.construct(DomainBuilders.java:364)
	at com.tngtech.archunit.core.importer.DomainBuilders$JavaMemberBuilder.build(DomainBuilders.java:196)
	at com.tngtech.archunit.core.importer.DomainBuilders$JavaMemberBuilder.build(DomainBuilders.java:128)
	at com.tngtech.archunit.core.importer.DomainBuilders$BuilderWithBuildParameter$BuildFinisher.build(DomainBuilders.java:841)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.createConstructors(ClassGraphCreator.java:315)
	at com.tngtech.archunit.core.domain.JavaClassMembers.create(JavaClassMembers.java:298)
	at com.tngtech.archunit.core.domain.JavaClass.completeMembers(JavaClass.java:1357)
	at com.tngtech.archunit.core.domain.DomainObjectCreationContext.completeMembers(DomainObjectCreationContext.java:90)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.completeClasses(ClassGraphCreator.java:150)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.complete(ClassGraphCreator.java:110)
	at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:63)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336)
	at com.tngtech.archunit.junit.ClassCache$CacheClassFileImporter.importClasses(ClassCache.java:121)
	at com.tngtech.archunit.junit.ClassCache$LazyJavaClasses.initialize(ClassCache.java:113)
	at com.tngtech.archunit.junit.ClassCache$LazyJavaClasses.get(ClassCache.java:102)
	at com.tngtech.archunit.junit.ClassCache.getClassesToAnalyzeFor(ClassCache.java:79)
	at com.tngtech.archunit.junit.ArchUnitTestDescriptor.lambda$createChildren$1(ArchUnitTestDescriptor.java:83)
	at com.tngtech.archunit.thirdparty.com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.tngtech.archunit.junit.ArchUnitTestDescriptor$ArchUnitRuleDescriptor.execute(ArchUnitTestDescriptor.java:160)
	at com.tngtech.archunit.junit.ArchUnitTestDescriptor$ArchUnitRuleDescriptor.execute(ArchUnitTestDescriptor.java:143)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by hankem** [comment] 2021-07-16 05:57
Just FYI: I could reproduce the issue with the following minimal example (but haven't analyzed it yet):
<details><summary><code>build.gradle</code></summary>

```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.firebase:firebase-admin:7.3.0'
    testCompile 'com.tngtech.archunit:archunit:0.20.0'
    testCompile 'org.apache.logging.log4j:log4j-slf4j-impl:2.14.1'
}

task runTest(type: JavaExec) {
    dependsOn compileTestJava
    classpath sourceSets.test.runtimeClasspath
    main = "Issue637"
}
```

</details>

<details><summary><code>src/test/java/Issue637.java</code></summary>

```java
class Issue637 {
    public static void main(String[] args) {
        new com.tngtech.archunit.core.importer.ClassFileImporter()
            .importPackagesOf(com.google.firebase.messaging.Message.class);
    }
}
```

</details>

<details><summary><code>src/test/resources/log4j2.xml</code></summary>

```xml
<Configuration>
  <Appenders>
    <Console name="Console"/>
  </Appenders>
  <Loggers>
    <Root level="warn">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
```

</details>

**Comment by codecholeric** [comment] 2021-07-16 06:25
Hmm, sorry for the inconvenience!! I'll take a look today! I added this check, because I wanted to know that my assumption was correct, seems like I didn't understand it completely after all :disappointed:

**Comment by hankem** [comment] 2021-07-16 07:56
@codecholeric, just in case this helps: I noticed that
```
com.tngtech.archunit.core.importer.ClassFileImportRecord$EnclosingDeclarationsByInnerClasses.registerEnclosingClass
```
is called twice with identical values
* `innerName="com.google.firebase.messaging.Message$1"` and
* `outerName="com.google.firebase.messaging.Message"`,

– namely
1. from `JavaClassProcessor.visitOuterClass(JavaClassProcessor.java:205)`, 
2. from `JavaClassProcessor.visitInnerClass(JavaClassProcessor.java:185)`.

**Comment by hankem** [comment] 2021-07-16 08:59
I didn't understand yet why `JavaClassProcessor.visitOuterClass` is triggered for _those_ synthetic classes – I think `com.google.firebase.messaging.Message$1` is used for the [invocation of the private constructor](https://github.com/firebase/firebase-admin-java/blob/v7.3.0/src/main/java/com/google/firebase/messaging/Message.java#L159) `new Builder()` – _but not for others that I've seen so far._ (Maybe it's because `firebase-admin:7.3.0` was built with JDK `1.7.0_302`?)

Anyways, a simple fix could be to weaken the check in `EnclosingDeclarationsByInnerClasses.registerEnclosingClass`:
```diff
-             checkArgument(!innerClassNameToEnclosingClassName.containsKey(innerName),
+             checkArgument(!innerClassNameToEnclosingClassName.containsKey(innerName)
+                             || innerClassNameToEnclosingClassName.get(innerName).equals(outerName),
                      "Can't register multiple enclosing classes, this is likely a bug!");
```

**Comment by codecholeric** [comment] 2021-07-16 09:27
Yes, I just wanted to understand the reason :thinking: Because we have test cases that look very similar, analogous bytecode if I check it with `javap`. Yet `visitInnerClass` is not called in that case :confused: I just would like to understand where it's coming from. But I have to admit that the exact semantics when `visitInnerClass` vs `visitOuterClass` is called is still a little bit of a mystery to me. We have so many test cases with anonymous and local classes, yet this doesn't break in any. And we run those tests with all sorts of JDK versions :thinking: I really would like to understand ASM here. What is the difference in these classes that cause this behavior. But if I can't figure it out, maybe I'll open an issue with ASM and ask why the visitor behaves differently for these seemingly identical bytecode patterns.
But of course, an easy fix would be to revert the behavior to the old version and simply accept registering the same enclosing class multiple times :man_shrugging:

**Comment by codecholeric** [comment] 2021-07-16 09:28
I just wish I could reproduce it with a simple test :thinking: I'll see if I can strip this Firebase example down to a simple version that shows the same problem.

**Comment by codecholeric** [comment] 2021-07-16 10:48
Okay, I think I understand why it behaves differently. When I create the same pattern (class with builder resulting in an anonymous class to access the private constructor) within the ArchUnit tests, I get this `InnerClasses` entry:

```
InnerClasses:
  static #1;                              // class com/tngtech/archunit/core/importer/testexamples/innerclassimport/Message$1
```

When I look at the bytecode of the real `Message$1` I see the following:

```
InnerClasses:
  static #1 of #6;                        // class com/google/firebase/messaging/Message$1 of class com/google/firebase/messaging/Message
```

Looking at the [spec](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.6) I see

```
outer_class_info_index

If C is not a member of a class or an interface (that is, if C is a top-level class or interface (JLS §7.6) or a local class (JLS §14.3) or an anonymous class (JLS §15.9.5)), the value of the outer_class_info_index item must be zero.

Otherwise, the value of the outer_class_info_index item must be a valid index into the constant_pool table, and the entry at that index must be a CONSTANT_Class_info structure representing the class or interface of which C is a member.
```

So I would guess that by spec every anonymous class (and that is exactly what `Message$1` looks like, even though it's synthetic) should have `outer_class_info_index == 0`. However, `javap` suggests to me that in the Firebase `Message$1` the `outer_class_info_index` is not zero, but points to `com.google.firebase.messaging.Message`. By that it gets picked up twice by ASM (in `visitOuterClass` and `visitInnerClass`) causing the exception.

I did some quick check and it looks like JDK 7 treats this case differently from later JDKs. At least JDK 15 treats a class like `Message$1` as anonymous and does not set an outer class attribute. However, JDK 7 sets this attribute. I guess that this unfortunately a hole within the ArchUnit tests, because we compile the classes with JDK 15 but target compatibility 7, then run the tests with a JRE 7. So we have no tests to see how JDK 7 would actually compile the classes, and JDK 15 seems to compile them differently, even if the target compatibility is 7 :thinking: To have more realistic tests we would really have to use the test JDK selectively to compile the test classes, but that would be a pretty complicated setup I think...

For now I will make this resilient against duplicate registration of the same outer class to support the older JDK versions again.

**Comment by codecholeric** [comment] 2021-07-16 12:48
Should be fixed with https://github.com/TNG/ArchUnit/releases/tag/v0.20.1
If not feel free to reopen this issue :wink:

**Closed by codecholeric** 2021-07-16 12:48 UTC
