### ISSUE TITLE
JavaAnnotation always populates properties with default values since 0.15.0

### ISSUE THREAD

**Issue by heri333** [TNG/ArchUnit#499] opened 2021-01-04 14:12 UTC
Some libraries check whether properties are set *explicitly* on annotations. An example is the mapstruct [Mapper](https://github.com/mapstruct/mapstruct/blob/master/core/src/main/java/org/mapstruct/Mapper.java) annotation where the `unmappedTargetPolicy` does only override the `config` when set *explicitly*.

In ArchUnit **0.14.1** it could be checked whether the property was specified by the developer like `((JavaAnnotation)item).get("unmappedTargetPolicy").isPresent()`.

In ArchUnit **0.15.0** `isPresent()` is always `true`, since the property is initialized with the default value specified in the annotation.

Since the library does check whether the property was set, we need a way to also check this via ArchUnit to ensure the desired configuration. Since this worked in past versions, this looks like a regression to me. Or is there any new way to check this with ArchUnit?

**Comment by hankem** [comment] 2021-01-04 20:28
I can confirm that the behaviour changed from ArchUnit 0.14.1 to 0.15.0.
I personally agree with you that `isPresent()` should indicate whether the annotation's property is defined or not.

But irrespective of the desired behavior, I believe that the underlying issue has actually been there before: Even with ArchUnit 0.14.1, the following example, which explicitly imports `@Mapper`, fails to recognize that  `InvalidMapper` defines no `unmappedTargetPolicy`:
```java
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.junit.ArchUnitRunner;
import com.tngtech.archunit.lang.ArchRule;
import org.junit.runner.RunWith;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

import static com.tngtech.archunit.base.DescribedPredicate.describe;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;

@RunWith(ArchUnitRunner.class)
@AnalyzeClasses(packagesOf = {Issue499.class, Mapper.class})
public class Issue499 {
    @ArchTest
    static final ArchRule mapper_should_define_unmappedTargetPolicy =
        classes()
            .that().areAnnotatedWith(Mapper.class)
            .should().beAnnotatedWith(describe("an annotation with unmappedTargetPolicy property",
                annotation -> annotation.get("unmappedTargetPolicy").isPresent()
            ));

    @Mapper(unmappedTargetPolicy = ReportingPolicy.WARN)
    static class ValidMapper {
    }

    @Mapper
    static class InvalidMapper {
    }
}
```

The default value of `unmappedTargetPolicy` is not "known" to ArchUnit 0.14.1 if `@Mapper` is not imported, i.e. when using:
```java
@AnalyzeClasses(packagesOf = Issue499.class)
```

With #342 (fixed in ArchUnit 0.15.0), `@Mapper` is automatically imported.

**Comment by hankem** [comment] 2021-01-04 21:49
After 22ef516bbfd0b491f0b8150cdc14dbd9e4090ea8, `JavaAnnoation` internally stores the explicit property values, so you can use this workaround with ArchUnit 0.15.0:
```java
    classes()
        .that().areAnnotatedWith(Mapper.class)
        .should().beAnnotatedWith(describe("an annotation with unmappedTargetPolicy property",
            annotation -> {
                try {
                    Field field = annotation.getClass().getDeclaredField("values");
                    field.setAccessible(true);
                    Object explicitPropertyValue = ((Map) field.get(annotation)).get("unmappedTargetPolicy");
                    return explicitPropertyValue != null;
                } catch (IllegalAccessException | NoSuchFieldException e) {
                    throw new RuntimeException(e);
                }
            }
        ));
```

**Comment by heri333** [comment] 2021-01-04 22:36
Your example fails correctly in 0.14.1 (and does not detect `InvalidMapper` in 0.15.0), slightly changed:
```java
package com.tngtech.archunit;

import com.tngtech.archunit.core.importer.ImportOption.DoNotIncludeJars;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

import static com.tngtech.archunit.base.DescribedPredicate.describe;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;

@AnalyzeClasses(packagesOf = Issue499.class, importOptions = {DoNotIncludeJars.class})
public class Issue499 {

    @ArchTest
    static final ArchRule mapper_should_define_unmappedTargetPolicy =
            classes()
                    .that().areAnnotatedWith(Mapper.class)
                    .should().beAnnotatedWith(describe("an annotation with unmappedTargetPolicy property",
                    annotation -> annotation.get("unmappedTargetPolicy").isPresent()
            ));

    @Mapper(unmappedTargetPolicy = ReportingPolicy.WARN)
    static class ValidMapper {
    }

    @Mapper
    static class InvalidMapper {
    }
}
```

But your workaround works in 0.15.0, thanks!

**Comment by codecholeric** [comment] 2021-01-05 13:45
From my point of view I can only say, that `isPresent()` was never meant to indicate, if a property was explicitly set, or not. Because the `Optional` was meant to indicate, if an annotation has a property with this name or not. Since an annotation property value can never be `null`, it felt fair to me, that `JavaAnnotation.get("foo")` would return an `Optional.of(value)`, if and only if the annotation has a property `foo` (which can then never be absent, either by default value or explicitly set).
As @hankem pointed out, if it worked that way in ArchUnit `0.14.1`, this was purely accidental. Because I refactored the way annotation default values are imported, so it seems like some default values can now be resolved that could not be resolved with the old version. ArchUnit `0.15.0` also imports more annotation related properties from the classpath, even if not explicitly imported.
That said, now that I know this is a use case :wink: (and a completely reasonable one for sure), it would be no problem to add a method `boolean hasExplicitlyDeclaredProperty(name)` or `Optional<Object> getExplicitlyDeclaredProperty(name)` (any good suggestions for the name?)
Would one or both of these methods be reasonable for this use case?

**Comment by heri333** [comment] 2021-01-08 09:07
Yes, those methods sound very reasonable, I would prefer at least `Optional<Object> getExplicitlyDeclaredProperty(name)` to get direct access to the flexible `Optional` methods.

**Closed** 2021-02-20 19:51 UTC
