### ISSUE TITLE
Meta-annotations are not discovered

### ISSUE THREAD

**Issue by vprudnikov** [TNG/ArchUnit#274] opened 2019-12-06 10:27 UTC
Hi, 

I have an issue with meta-annotations:

**Finder.java**

```
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.TYPE)
@Component
@Transactional(readOnly = true)
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Documented
public @interface Finder {
}
```

**MyFinder.java**

```
import org.springframework.transaction.annotation.Transactional;

@Finder
public class MyFinder {
}
```

**ArchitectureTest.java**

```
import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchRules;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import DDDArchTests;

@AnalyzeClasses(packagesOf = ArchitectureTest.class,
                importOptions = {
                        ImportOption.DoNotIncludeArchives.class,
                        ImportOption.DoNotIncludeTests.class
                }
)
class ArchitectureTest {

    @ArchTest
    public static final ArchRules dddTests = ArchRules.in(DDDArchTests.class);
}
```

**DDDArchTests.java**

```
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.springframework.transaction.annotation.Transactional;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.methods;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class DDDArchTests {

...
    @ArchTest
    public static final ArchRule rule =
            classes().that().areAnnotatedWith(Finder.class)
                    .should().beMetaAnnotatedWith(Transactional.class);
...
```

I expect that this rule doesn't fail BUT:
`Rule 'classes that are annotated with @Finder should be meta-annotated with @Transactional' was violated ... Class <...MyFinder> is not meta-annotated with @Transactional in (MyFinder.java:0)`

**Is it a bug or I misunderstand the API?**

P.S. I tried to debug it a bit and I could also see that such annotations like Spring's `@Configuration` don't contain information that they annotated with `@Component` annotation.

**Comment by hankem** [comment] 2019-12-06 11:01
Hm, strange: I've tried to reproduce the issue, but failed.

I first thought that it could be related to Spring classes not being imported (cf. [ArchUnit User Guide: Dealing with Missing Classes](https://www.archunit.org/userguide/html/000_Index.html#_dealing_with_missing_classes)), but couldn't even get the error when using
`resolveMissingDependenciesFromClassPath=false`.

As your example does not contain `import` statements:
Are you sure that both `Finder` and the rule refer to the same `Transactional` class?

**Comment by vprudnikov** [comment] 2019-12-06 11:24
> Hm, strange: I've tried to reproduce the issue, but failed.
> 
> I first thought that it could be related to Spring classes not being imported (cf. [ArchUnit User Guide: Dealing with Missing Classes](https://www.archunit.org/userguide/html/000_Index.html#_dealing_with_missing_classes)), but couldn't even get the error when using
> `resolveMissingDependenciesFromClassPath=false`.
> 
> As your example does not contain `import` statements:
> Are you sure that both `Finder` and the rule refer to the same `Transactional` class?

I've updated a description. Could you please take a look? Does it help?

**Comment by hankem** [comment] 2019-12-06 11:52
Sorry, I still can only reproduce the failure when I actually remove `Finder`'s `@Transactional` annotation (both when I run the test from IntelliJ IDEA or with gradle).

Is there any chance that the test pick's up an outdated definition of `public @interface Finder`?

**Comment by vprudnikov** [comment] 2019-12-06 12:01
> Sorry, I still can only reproduce the failure when I actually remove `Finder`'s `@Transactional` annotation (both when I run the test from IntelliJ IDEA or with gradle).
> 
> Is there any chance that the test picks up an outdated definition of `public @interface Finder`?

I don't think so. I remember my tests failed when I was trying to check Spring controllers' methods whether they are META-annotated with `@RequestMepping` annotation.

It looks like I need to prepare a downloadable test app...

**Comment by vprudnikov** [comment] 2019-12-06 13:02
[meta-annotation-demo.zip](https://github.com/TNG/ArchUnit/files/3932240/meta-annotation-demo.zip)

@hankem 
Please take a look at it and run `./mvnw clean install`

It looks like there is a problem with modules because the test works fine if I have everything in one module.

**Comment by hankem** [comment] 2019-12-06 13:38
The `ArchitectureTest` works for me. I'm using `openjdk 11.0.1`.
(`DemoApplicationTests.contextLoads` fails, though... 😉)

Which Java version are you using?

**Comment by hankem** [comment] 2019-12-06 14:09
Hah!
It turns out that I _do indeed get your failure_ when running `./mvnw clean install` as you specified.

I initially didn't want to spoil my `~/.m2`, and just ran `./mvnw clean test` – which doesn't fail... WTF!?!
It seems that Maven builds a different classpath for `install` than for `test`. 

Once accepting this, the issue seems to be caused by the `ImportOption.DoNotIncludeArchives` in your definition
```
@AnalyzeClasses(packagesOf = ArchitectureTest.class,
                importOptions = {
                        ImportOption.DoNotIncludeArchives.class,
                        ImportOption.DoNotIncludeTests.class
                }
)
```

Removing `DoNotIncludeArchives` here makes the test pass for me – for both `./mvnw clean install` and `./mvnw clean test`, by the way... 😉

**Comment by vprudnikov** [comment] 2019-12-06 15:21
@hankem thank you for your feedback. Indeed, that fixes the problem in the demo-project!

HOWEVER, it doesn't fix the problem in my real project :( Everything works as expected except meta-annotations: both IDEA and mvn complain.

I don't know what I can do....

**Comment by vprudnikov** [comment] 2019-12-06 15:32
[meta-annotations-demo-1.zip](https://github.com/TNG/ArchUnit/files/3932854/meta-annotations-demo-1.zip)

@hankem I replicated a package structure from the real project, and it started failing. Could you please check now?

Thank you!

**Comment by hankem** [comment] 2019-12-06 16:48
This is now due to the fact that `com.starter.cqrs.Finder` is not imported by ArchUnit with this declaration:
```
@AnalyzeClasses(
        packagesOf = {com.user.ArchitectureTest.class},
        importOptions = {ImportOption.DoNotIncludeArchives.class,ImportOption.DoNotIncludeTests.class}
)
```

I'd hope that the following works:
```
@AnalyzeClasses(
        packagesOf = {com.user.ArchitectureTest.class, com.starter.cqrs.Finder.class},
        importOptions = {ImportOption.DoNotIncludeTests.class}
)
```

----

I need to check whether the [default configuration `resolveMissingDependenciesFromClassPath=true`](https://www.archunit.org/userguide/html/000_Index.html#_dealing_with_missing_classes) should actually make this unnecessary.
Maybe @codecholeric knows that from the top of his head? 😉

**Comment by vprudnikov** [comment] 2019-12-06 20:19
@hankem thank you, it works!

However, maybe I don't get an idea, BUT I want to check classes that reside only under `com.user` package.
If I understood it correctly, now it analyses classes that exist even in another module. For big projects it can affect performance and... I feel that it's semantically incorrect to check classes in other libraries. Instead, I should have (and I have) archunit test per module.

What do you think?

**Comment by vprudnikov** [comment] 2019-12-19 12:12
@hankem . do you have any updates?
Thank you! :)

**Comment by hankem** [comment] 2019-12-20 07:59
Sorry, I wasn't able to look much into this during the last two weeks; also because I'm actually not an expert with ArchUnit's class file import... 😉

So far, I've found [a test](https://github.com/TNG/ArchUnit/blob/v0.12.0/archunit/src/test/java/com/tngtech/archunit/core/importer/ClassFileImporterTest.java#L872-L890) from the early days of ArchUnit (January 2017 😃) showing that annotations are _kind of incomplete_ when the annotation classes are not imported themselves.
I need to see whether the `resolveMissingDependenciesFromClassPath` feature could be applied in this case, too.

**Comment by codecholeric** [comment] 2020-01-16 15:06
At the moment meta-annotations are not resolved, even if `resolveMissingDependenciesFromClassPath` is set to true. Originally I cut off dependencies after a depth of one, i.e. if your method calls a method of a class not imported, that class will be imported with `resolveMissingDependenciesFromClassPath`, but not any transitive dependencies (as the consequences are hard to figure out).
With annotations I kept it the same, meta-annotations are treated like transitive dependencies and have thus to be imported if you want to access them.
However (as discussed with @hankem), we could maybe treat annotations the same way as super classes. Because the class hierarchy is completely resolved, I think doing the same with annotations might drastically reduce confusion (since a lot of questions so far have targeted that area, where annotations were missing from the import).
So in a similar place where `completeHierarchies` is executed and super classes / interfaces are recursively imported with the current `ClassResolver`, we could do the same for annotations, resolving as well meta-annotations as parameters. Might need some testing, if this could explode with annotation heavy frameworks, but I think it should be okay (at least in my experience the set of all classes participating in annotations as meta-annotations or parameters is not so huge that it makes a real difference, and if it does one can always reconfigure the `ClassResolver`).

**Comment by codecholeric** [comment] 2020-01-16 15:17
@vprudnikov BTW, there already is an issue to allow specifying an additional context, e.g. your `@Finder` -> #142
I'm planning on adding this to the next release, since it would be pretty useful to just pick some single additional relevant classes.

Anyway, if this really affects your performance, since you have a huge number of classes in the same root as `@Finder`, you can apply a hack at the moment, by excluding the classes via a custom `ImportOption`:

```
@AnalyzeClasses(
        packagesOf = {com.user.ArchitectureTest.class, com.starter.cqrs.Finder.class},
        importOptions = {ImportOption.DoNotIncludeTests.class, ExcludeUnnecessaryInfrastructure.class}
)
class SomeTest {}

// ...

class ExcludeUnnecessaryInfrastructure implements ImportOption {
    @Override
    public boolean includes(Location location) {
        return !location.contains("/com/starter/cqrs/") || location.contains("/com/starter/cqrs/Finder");
    }
}
```

**Comment by vprudnikov** [comment] 2020-01-16 15:40
@codecholeric , thanks for your answer!

I'm pretty sure that the resolution of meta-annotations could be a nice feature that eliminates any confusion.

I will wait for the next release. My current 'hack' is to lift meta-annotations to classes and explicitly require them in an ArchUnit test.

When this feature is ready I will just start using meta-annotations.

Thanks again and good luck!

**Comment by codecholeric** [comment] 2020-04-09 15:55
I'll close this in favor of #342

**Closed by codecholeric** 2020-04-09 15:55 UTC
Labels: enhancement, help wanted
